import { motion } from "framer-motion";
import { ExternalLink, Github } from "lucide-react";

const projects = [
  {
    title: "Interview Flow",
    description:
      "Developed a full-stack remote interview platform with real-time video communication and backend functionality.",
    tech: ["Next.js", "TypeScript", "Stream", "Convex", "Clerk"],
    links: {
      github: "https://github.com/varshilmedidhi/InterviewFlow",
      live: "",
    },
  },
  {
    title: "Vibe-Vault",
    description:
      "Engineered a real-time chat application with <100ms message delivery latency and 99.9% uptime.",
    tech: ["MERN", "Socket.io", "Tailwind"],
    links: {
      github: "https://github.com/varshilmedidhi/Vibe-Vault",
      live: "",
    },
  },
  {
    title: "Data Lense",
    description:
      "Engineered a desktop application for importing CSV files, cleaning datasets, and generating interactive charts.",
    tech: ["Python", "Tkinter", "Matplotlib", "Pandas"],
    links: {
      github: "https://github.com/varshilmedidhi/Data-analysis-project",
      live: "",
    },
  },
  {
    title: "Pure Page",
    description:
      "Pure Page is a JavaScript Ad Blocker project aimed at enhancing the user experience while browsing by blocking intrusive advertisements on web pages. The tool leverages JavaScript's DOM manipulation capabilities to detect and remove ad elements dynamically.",
    tech: ["JavaScript", "Browser Extensions"],
    links: {
      github: "https://github.com/varshilmedidhi/Ad-blocker",
      live: "", // Update with the live link if available
    },
  },
  {
    title: "Simon Game",
    description:
      "The Simon Game is a memory-based game where players must replicate a sequence of colors and sounds generated by the game. The sequence increases in complexity as the game progresses, challenging the player's ability to remember and replicate the pattern.",
    tech: ["HTML", "CSS", "JavaScript"],
    links: {
      github: "https://github.com/varshilmedidhi/simongame",
      live: "https://varshilmedidhi.github.io/simongame/",
    },
  },
];

const Projects = () => {
  return (
    <section id="projects" className="py-20 px-6">
      <div className="container mx-auto">
        <h2 className="section-title text-center mb-12">Project Album</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group relative p-6 rounded-xl border border-secondary/10 bg-secondary/5 hover:bg-secondary/10 transition-all duration-300"
            >
              <div className="space-y-4">
                <h3 className="text-xl font-bold tracking-tight">
                  {project.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {project.description}
                </p>

                <div className="flex flex-wrap gap-2">
                  {project.tech.map((tech, techIndex) => (
                    <span
                      key={techIndex}
                      className="px-3 py-1 bg-primary/10 text-primary text-xs font-medium rounded-full"
                    >
                      {tech}
                    </span>
                  ))}
                </div>

                <div className="flex gap-4 pt-2">
                  <a
                    href={project.links.github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-primary transition-colors"
                  >
                    <Github className="w-5 h-5" />
                  </a>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;
